# Generated by Django 3.0.8 on 2020-08-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='hint',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
