# Generated by Django 3.0.8 on 2020-08-12 20:20

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20200812_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
