# Generated by Django 3.0.8 on 2020-08-20 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_book_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='amount',
        ),
    ]
