# Generated by Django 3.0.8 on 2020-08-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_remove_book_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='son_durum',
            field=models.ImageField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
