# Generated by Django 3.0.8 on 2020-08-19 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderbook',
            name='fiyat',
        ),
    ]
